name: generate animation

on:
  # rodar automaticamente a cada 24 horas
  schedule:
    - cron: "0 */24 * * *" 
  
  # permite rodar manualmente a qualquer momento
  workflow_dispatch:
  
  # roda a cada push na branch main
  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # gera o jogo do pacman com as contribuições do usuário
      - name: generate github-contribution-grid-snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Edupizzol
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        
      # envia o arquivo gerado para a branch 'output'
      - name: push github-contribution-grid-snake to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
